# Generated by Django 5.1.3 on 2024-11-20 23:04

import app_users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_users.usermodel',),
            managers=[
                ('objects', app_users.managers.UserModelManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_users.usermodel',),
            managers=[
                ('objects', app_users.managers.CustomerManager()),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
